<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by www.codechief.org</title>
</head>
<body>
    <h1>{{ $user['indicado'] }}</h1>
    <p>{{ $pontuacao['pontuacao'] }}</p>
    <p>{{ $empresa['empresa'] }}</p>
    <p>{{ $nova_pontuacao['nova_pontuacao'] }}</p>
    <p>Thank you</p>
</body>
</html>